### ISSUE TITLE
Document Size CosmoDB max 2mb

### ISSUE THREAD

**Issue by jordilaforge** [baloise/this-or-that#146]
There is an error on prod wenn you want to persist the survey. ComsoDB ist supporting documents up to 2mb. But a whole survey is a lot more. Either we change to a different hoster or we refactor the application to safe images outside of a survey.

**Comment by RCBiczok** [comment]
Maybe Azure Blob would be an good alternative? On the other hand, if it is easy to get a File-System quota for the images, then saving them separately would be probably the most pragmatic solution for now. Especially if we consider switching the Cloud provider.

**Comment by jordilaforge** [comment]
yes I think so too we should save all image in a separate collection
